[app]
name = "demo"
host = "0.0.0.0"
port = "8050"
key  = "this is your app key"

[mysql]
host = "192.168.10.10"
port = "3306"
username = "go-cmdb"
password = "Ren910202."
database = "go_db"

[log]
level = "debug"
path_dir = "./logs"
format = "text"
to = "stdout"